spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sprint02
        username: root
        password: 
    jpa:
        hibernate:
            ddlAuto: update
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        showSql: true
